import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "../globals.css";
import { Header } from "@/components/header";
import { Suspense } from "react";

const nunito = Nunito({
    subsets: ["cyrillic"],
    variable: "--font-nunito",
    weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    modal,
}: Readonly<{
    children: React.ReactNode;
    modal: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={nunito.className}>
                <div className="wrapper bg-white w-7/8 mx-auto rounded-md shadow-2xl shadow-black  mt-10">
                    {/* Тут рендерится @modal */}
                    {modal}
                    <Header />
                    <main>{children}</main>
                </div>
            </body>
        </html>
    );
}
