import { Container } from "@/components/container";
import { Header } from "@/components/header";
import { Metadata } from "next";
import { Suspense } from "react";
import "../../app/globals.css";
import { Toaster } from "react-hot-toast";
import { Providers } from "@/components/provider/main-provider";

export const metadata: Metadata = {
  title: "Next Pizza | Корзина",
  description: "Generated by create next app",
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-[#f0dedf] pb-10">
          <Providers>
            <Container>
              <Suspense>
                <Header className="border-b-gray-200" />
              </Suspense>
              {children}
            </Container>
          </Providers>
        </main>
      </body>
    </html>
  );
}
